name: turquoise
base-image: ghcr.io/ublue-os/kinoite-main
fedora-version: 38
description: A customization over ublue starting point with Positivo touchscreen drivers for my personal usage 

scripts:
  pre:
    - autorun.sh
  post:
    - autorun.sh
  
rpm:
  repos:
 
  install:
    - python3-pip
    - waydroid
    - podman-docker
    - iwd
    - podman-plugins
    - podman-tui
    - tmux
    - cockpit
    - cockpit-podman
    - tailscale
 
  remove:
    - firefox
    - firefox-langpacks
    - wpa_supplicant

firstboot:
  yafti: true
  flatpaks:
    - io.github.celluloid_player.Celluloid
    - org.kde.krita
    - com.github.libresprite.LibreSprite
    - com.github.wwmm.easyeffects
    - io.github.Bavarder.Bavarder
    - io.github.shiftey.Desktop
    - io.github.wereturtle.ghostwriter
    - org.audacityteam.Audacity
    - org.cockpit_project.CockpitClient
    - org.gabmus.whatip
    - org.gimp.GIMP
    - org.gnome.Boxes
    - org.gnome.meld
    - org.inkscape.Inkscape
    - org.kde.alligator
    - org.kde.kasts
    - org.kde.kclock
    - org.kde.kdenlive
    - org.kde.kleopatra
    - org.kde.koko
    - org.kde.krita
    - org.kde.kweather
    - org.kde.neochat
    - org.kde.okular
    - org.kde.tokodon
    - org.kde.vvave
    - org.keepassxc.KeePassXC
    - org.mozilla.Thunderbird
    - org.rncbc.qpwgraph
    - org.videolan.VLC
