name: turquoise
base-image: ghcr.io/ublue-os/beyond
fedora-version: 38
description: A customization over ublue starting point with Positivo touchscreen drivers for my personal usage 

scripts:
  pre:
    - autorun.sh
  post:
    - autorun.sh
  
rpm:
  install:
    - python3-pip
    - libadwaita
    - zenity
    - waydroid
    - podman-docker
    - iwd
    - podman-plugins
    - podman-tui
    - tmux
    - cockpit
    - cockpit-podman
    - tailscale
    - gnome-tweaks
    - gnome-kiosk
    - gnome-kiosk-script-session
 
  remove:
    - wpa_supplicant

firstboot:
  yafti: true
  flatpaks:
