name: turquoise
base-image: ghcr.io/ublue-os/kinoite-main
fedora-version: 38
description: A customization over ublue starting point with Positivo touchscreen drivers for my personal usage 

scripts:
  pre:
    - autorun.sh
  post:
    - autorun.sh
  
rpm:
  repos:
 
  install:
    - waydroid
    - podman-docker
    - iwd
    - podman-plugins
    - podman-tui
    - tmux
    - cockpit
    - cockpit-podman
    - tailscale
 
  remove:
    - firefox
    - firefox-langpacks
    - wpa_supplicant

firstboot:
  yafti: false
  flatpaks:
    - io.github.celluloid_player.Celluloid
    - org.kde.krita
